[package]
name = "chalk-wasm"
version = "0.1.0"
edition = "2024"
authors.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
chalk-core = { path = "../chalk-core" }

[lints]
workspace = true
